data = [
    {'name': 'Instagram', 'follower_count': 670, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 630, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower_count': 500, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower_count': 430, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 400, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 395, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 370, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Beyoncé', 'follower_count': 325, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Nike', 'follower_count': 310, 'description': 'Sportswear brand', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 295, 'description': 'Model and TV personality', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 290, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'National Geographic', 'follower_count': 285, 'description': 'Magazine and media company', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 280, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Zendaya', 'follower_count': 180, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 170, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 160, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 150, 'description': 'Singer', 'country': 'Colombia'},
    {'name': 'Miley Cyrus', 'follower_count': 145, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 130, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Chris Hemsworth', 'follower_count': 120, 'description': 'Actor', 'country': 'Australia'},
    {'name': 'Billie Eilish', 'follower_count': 110, 'description': 'Musician', 'country': 'United States'},
    {'name': 'NASA', 'follower_count': 100, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Emma Watson', 'follower_count': 95, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'Priyanka Chopra', 'follower_count': 90, 'description': 'Actress', 'country': 'India'},
    {'name': 'David Beckham', 'follower_count': 85, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'Will Smith', 'follower_count': 82, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Shawn Mendes', 'follower_count': 78, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Zlatan Ibrahimović', 'follower_count': 60, 'description': 'Footballer', 'country': 'Sweden'},
    {'name': 'Tom Holland', 'follower_count': 58, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Anushka Sharma', 'follower_count': 63, 'description': 'Actress', 'country': 'India'},
    {'name': 'Blackpink', 'follower_count': 55, 'description': 'K-pop group', 'country': 'South Korea'},
    {'name': 'Jungkook', 'follower_count': 52, 'description': 'K-pop artist', 'country': 'South Korea'},
    {'name': 'RM (BTS)', 'follower_count': 50, 'description': 'K-pop artist', 'country': 'South Korea'},
    {'name': 'V (BTS)', 'follower_count': 51, 'description': 'K-pop artist', 'country': 'South Korea'},
    {'name': 'IU', 'follower_count': 45, 'description': 'Singer and actress', 'country': 'South Korea'},
    {'name': 'Gigi Hadid', 'follower_count': 80, 'description': 'Model', 'country': 'United States'},
    {'name': 'Hrithik Roshan', 'follower_count': 45, 'description': 'Actor', 'country': 'India'},
    {'name': 'Deepika Padukone', 'follower_count': 80, 'description': 'Actress', 'country': 'India'},
    {'name': 'Alia Bhatt', 'follower_count': 80, 'description': 'Actress', 'country': 'India'},
    {'name': 'Gal Gadot', 'follower_count': 100, 'description': 'Actress', 'country': 'Israel'},
    {'name': 'Robert Downey Jr.', 'follower_count': 90, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Taylor Swift', 'follower_count': 290, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Doja Cat', 'follower_count': 35, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Jisoo (Blackpink)', 'follower_count': 77, 'description': 'K-pop artist', 'country': 'South Korea'},
    {'name': 'Lisa (Blackpink)', 'follower_count': 97, 'description': 'K-pop artist', 'country': 'Thailand'},
    {'name': 'Rosé (Blackpink)', 'follower_count': 70, 'description': 'K-pop artist', 'country': 'New Zealand'},
    {'name': 'Jennie (Blackpink)', 'follower_count': 85, 'description': 'K-pop artist', 'country': 'South Korea'},
    {'name': 'Bad Bunny', 'follower_count': 50, 'description': 'Musician', 'country': 'Puerto Rico'},
    {'name': 'Travis Scott', 'follower_count': 50, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Post Malone', 'follower_count': 65, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Karim Benzema', 'follower_count': 65, 'description': 'Footballer', 'country': 'France'},
    {'name': 'Neymar Jr', 'follower_count': 220, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Kourtney Kardashian', 'follower_count': 220, 'description': 'Reality TV star', 'country': 'United States'},
    {'name': 'Snoop Dogg', 'follower_count': 90, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Millie Bobby Brown', 'follower_count': 65, 'description': 'Actress', 'country': 'United Kingdom'}
]
